### ISSUE TITLE
Populate ABox from files

### ISSUE THREAD

**Issue by alex-mitrevski** [b-it-bots/mas_knowledge_base#2]
Related to https://github.com/b-it-bots/mas_knowledge_base/issues/1

To speed up the process of asserting knowledge in the ontology, it would be useful to be able to generate class and property assertions from configuration files.

For this, we need to:
1. define the format of the configuration files
2. write a small script that generates appropriate tags and adds them to the ontology

**Comment by argenos** [comment]
If this isn't a high priority, we can also do this for SDP WS19 I think

**Comment by alex-mitrevski** [comment]
Resolved by https://github.com/b-it-bots/mas_knowledge_base/pull/17
