### ISSUE TITLE
Define an ontology for our lab.

### ISSUE THREAD

**Issue by PatrickNa** [b-it-bots/mas_knowledge_base#6]
**Is your feature request related to a problem? Please describe.**
Ontologies most often contain environment specific information and since our lab is the environment in which develop, test and often also show demos, we should have specified ontology similar to the one we defined in Magdeburg (German Open 2019).

**Describe the solution you'd like**
Take the Magdeburg ontology as an example. 

**Additional context**
The ontology is in particular important for "where is this" and "find my mates".
Experts that should be kept in the loop are: @rhasel4s and @alex-mitrevski

**Comment by alex-mitrevski** [comment]
Resolved by https://github.com/b-it-bots/mas_knowledge_base/pull/13 and https://github.com/b-it-bots/mas_knowledge_base/pull/35

Note that the current ontology is not a complete model of our lab, but the relevant skeleton is already there and can be extended easily (hopefully).
